### ISSUE TITLE
Reobfuscate tabbychat

### ISSUE THREAD

**Issue by Dykam** [Dykam/tabbychat#20]
Say what?

**Comment by Dykam** [comment]
What would be best way to do this? I mainly focused on liteloader. @killjoy1221? Having never modded before (but plenty of java/bukkit), I was able to figure out most, except for the reobfuscation.

**Comment by mattmess1221** [comment]
You can either recompile it with mcp or use forgegradle, which I recommend.

**Comment by Dykam** [comment]
I want to target LiteLoader (as well), does that work with forgegradle?

**Comment by mattmess1221** [comment]
It should all work.  Soon, I'll do a PR with my changes for forge compat and a build.gradle.

**Comment by Dykam** [comment]
Ah, nice. I've been using maven to compile it myself, which works fine for compiling the decompiled Minecraft sources, and IntelliJ's own compiler to produce the litemod, but it's better to follow the standards (forgegradle)
