### ISSUE TITLE
Triple text entry bars/multiline entry bars

### ISSUE THREAD

**Issue by Dykam** [Dykam/tabbychat#24]
You can enter text in all, though it gets collapsed when you do.
- [x] Multiline entry should be single line
- [x] Background should be blank

**Comment by mattmess1221** [comment]
I think the issue is somewhere in the GuiChatTC class. In the drawScreen method.  The block on line 180, commented "Calculate positions of currently-visible input fields," tells me that something's incorrectly setting the inputList visible property to true.
