### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by mattmess1221** [Dykam/tabbychat#28]
Sent links are unclickable.  Adding support for /tellraw should fix it.

**Comment by Dykam** [comment]
As far as I know generating links is now server side, so my first assumption is that the link data is lost when receiving it. This is most likely happening in one of several places where I added temporary calls to `getFormattedText()` and `getUnformattedText()`. The TC core has to be rewritten to properly handle `IChatComponent`. This seems quite involved, especially where the code cuts the text into separate lines.

**Comment by Dykam** [comment]
One of the main offenders seem to be `TabbyChat.processChat(List<TCChatLine>)`, with these calls:
- `String TabbyChatUtils.chatLinesToString(List<TCChatLine>)`
- `String TabbyChat.processChatForFilters(String, List<String>)`
- `List<TCChatLine> TabbyChatUtils.stringToChatLines(int, String, int, boolean)`

**Comment by Dykam** [comment]
I just realized that in the code can be reduced, in that link execution is now part of core Minecraft I expect. That is, IChatComponents have an action property, which can be more than just links. I have not looked into how to execute those though. But we will have to identify what component someone clicked on and execute that action. In the same way hover-description has to be implemented.

**Comment by Dykam** [comment]
(I'll keep adding my findings until I have time to properly work on this):
`String TabbyChat.processChatForFilters(String, List<String>)` uses `TCChatFilter`s, which work on strings and modify the return value. I think our best bet is to first develop (or find?) a method to split a  `IChatComponent` up on character boundaries, like `IChatComponent[] split(IChatComponent, int...)`

**Comment by mattmess1221** [comment]
Testing this is going to be a bit harder.  For me at least, links in chat don't even work in vanilla singleplayer.  There's still the issue of the hover text.  As soon as we get that ironed out, I'll start working on the inline image viewing.

**Comment by mattmess1221** [comment]
https://bugs.mojang.com/browse/MC-30864

**Comment by Dykam** [comment]
The hover text thing and literally everything is related to the same core issue, and that is that we currently erase any meta-information by requesting the formatted string.

Step one is to fix the splitting trough the entire framework, so a IChatComponent ends up at the renderer. Spitting into the base code might be useful, but it is hard to reuse since we need custom highliting.
Step two is to properly handle it. The hovering. The clicking is is already in, sort of. We might need to map the IChatComponents to coordinates somehow.

**Comment by mattmess1221** [comment]
I've gotten links given from basic /tellraw commands to work.  Still working on this.  Unfortunately, I broke filters.

**Comment by Dykam** [comment]
What approach are you taking? I mean, how do you map x/y click to component?

**Comment by mattmess1221** [comment]
That part was actually working perfectly.  I learned that when I had it output the text when I clicked.  The issue was that the `ChatStyle` was being thrown away when it did the multi-line chat.  I think it also did it when it it parsed it for filters.

**Comment by Dykam** [comment]
But didn't it just run split on the flattened string instead of the component? Or is it using my custom component split? (I have no idea)

**Comment by mattmess1221** [comment]
I threw out your split and recoded it entirely.  It fixes the part that had to do with word wrap.

**Comment by Dykam** [comment]
Oops. That's odd, I tested it quite thoroughly. Where did it fail?

**Comment by mattmess1221** [comment]
I really had no idea how to use it, so I made it easier.

**Comment by Dykam** [comment]
Oh right. I started it with the wrong assumption, completely ignoring word wrap etc. This is a lot cleaner.

Edit: Nvm, getFormattedText was necessary for correct width.
Edit2: It can be optimized, I'll do that next week.

**Comment by mattmess1221** [comment]
Actually, thanks for having me look at that code.  I noticed that I forgot to remove `+ " " +`.  There's no need for that since I included the delimiter when I split the text.

**Comment by mattmess1221** [comment]
It looks like the click event is only showing up for the main component and none of the extras.  Working on it.

**Comment by mattmess1221** [comment]
Fixed completely via 86f4714012424365a8ffd34bdfb614d1dbdaa188
