### ISSUE TITLE
Send filter matches to all tabs crashes the client

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#35]
Making a new filter, then checking _Send matches to tab_, then checking _All tabs_, then triggering the filter, will make the client crash.

I can give crashlog if needed, but you should be able to recreate it?

**Comment by mattmess1221** [comment]
I didn't get a crash, but I ran out of memory.

**Comment by erock112233** [comment]
I have the same problem as killjoy, using the 1.6.4 liteloader version with the TPPI ftb pack.
