### ISSUE TITLE
Use commit number as revision?

### ISSUE THREAD

**Issue by mattmess1221** [Dykam/tabbychat#37]
For instance, currently, the number of commits is 345, so we would use that as the revision.

**Comment by Dykam** [comment]
The problem is that rebases can make the number jump around.

**Comment by mattmess1221** [comment]
I should reiterate.  The actual version number will stay at 1.11.0 until we change it.  That will be the release version.  We would use the number of commits as the revision number in the litemod.json at the time of release.

If we don't do this now, we should do it if we ever get to use a CI server, but not likely.
