### ISSUE TITLE
Support for client-side Forge commands

### ISSUE THREAD

**Issue by RoyCurtis** [Dykam/tabbychat#38]
Forge allows for client-side commands to be registered using `ClientCommandHandler.instance.registerCommand(command);`.

This is for mods that provide local client functionality through commands (e.g. Ingame XML Info and one of my own) even on multiplayer. However, Tabbychat seems to send chat directly to the server, [bypassing Forge's ClientCommandHandler](http://i.imgur.com/ZKZo783.png) and thus preventing such commands from working.

---

_Sidenote:_ I hope this feature request is appropriate whilst 1.7.2 TabbyChat is still a WIP. I have been following development and am glad to see TC still being kept up-to-date.

**Comment by mattmess1221** [comment]
What's the mod you're using that does this?  I know of some mods that register commands, but they're not updated yet.  I also think it's the server that registers commands.  I'm not familiar with the client-side commands.

**Comment by Dykam** [comment]
I guess we have to look into the base class, to see if we are bypassing a forge modification, or a change in vanilla behavior.

**Comment by mattmess1221** [comment]
I have a fix written up, but I need to test it before I commit and push.  What's the name of the mod you're using?

**Comment by RoyCurtis** [comment]
Sorry for the delayed response;
- [Ingame Info XML](https://mods.io/mods/1022-ingame-info-xml) - requires [LunatrisCore](https://mods.io/mods/1025-lunatriuscore). Example command is `/igi enable`
- [ShopsGuideCollector](https://github.com/RoyCurtis/ShopGuideCollector) - requires building, example command is `/sg save` or see [this part of the source](https://github.com/RoyCurtis/ShopGuideCollector/blob/master/src/main/java/roycurtis/shopguide/SGuide.java#L88)

Hope this helps!

Edit: [Here is a build of ShopGuideCollector](https://drive.google.com/file/d/0B7zQQWsMjPtwOTRaaEVwcFd4MFE/edit?usp=sharing) for testing

**Comment by mattmess1221** [comment]
Thanks for the links.  I have it mostly fixed, but Gradle won't reobf my reference to `ICommandSender.class`

I'll go ahead and commit it now and maybe we can figure it out later.
