### ISSUE TITLE
Chat rendered upside down

### ISSUE THREAD

**Issue by mattmess1221** [Dykam/tabbychat#40]
Pull the chat box all the way to the top of the screen, and it gets flipped.  New messages appear on the top instead of the bottom.

http://i.imgur.com/Mx3XP1Y.png

**Comment by Dykam** [comment]
Image is removed.

That's an odd bug, wondering how that's been introduced. I assume it always rendered upside down when at the top, but got some kind of correction which we removed during transition.

**Comment by mattmess1221** [comment]
Fixed.  I hate it when VoxelCam deletes the image when I press esc instead of back.

**Comment by Dykam** [comment]
I'm sorry I lack time to actually work on it, I'm at least trying to be a second brain ;)

**Comment by mattmess1221** [comment]
Fixed https://github.com/killjoy1221/tabbychat/commit/d019a7f92de3db2d5dd54bf02a0e13c103a7c024
