### ISSUE TITLE
Formatting resets after first word, and strikethrough does not work

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#42]
I have some chat stuff colored in my resource pack, and this is one; ![](http://i.imgur.com/MMwyRC4.png)
The whole line should be red.

Also, **strikethrough** text seems to just show up as... not strikethrough. It doesn't work.

**Comment by Dykam** [comment]
Only for texts in language files. Example, 'Plast Pack' with 'English (Color)'

**Comment by mattmess1221** [comment]
Until we get this fixed completely, add the &4 thing before every word.

**Comment by Brottweiler** [comment]
To clarify, strikethrough text does not show up as strikethrough, at all, anywhere. That's not just resource pack specific.

Also, those color code bug thing, also affects when I use `LOG()` with color codes with the macro mod, but the fix I assume will be the same.

**Comment by mattmess1221** [comment]
The strike-through works fine for me.  Remember, it's &m
