### ISSUE TITLE
not all links work

### ISSUE THREAD

**Issue by tsudeily** [Dykam/tabbychat#43]
Not every link works.. Ex: http://www.google.com works

www.google.com does not
google.com does not.

**Comment by Dykam** [comment]
Did you check if it differs from vanilla? As far as I am aware the server determines entirely what is a link and what isn't.

We only process text which has annotations like "open this when clicking"  and "show that when hoveren" .

**Comment by tsudeily** [comment]
Well I fill silly now. No vanilla doesn't allow www.google.com to work

Sorry for wasting your time. :\

**Comment by mattmess1221** [comment]
It's hard to verify links if it doesn't have a http:// in front of it.

@Dykam In 29b7c0c4035e0d7bae1f089d86c84581aa1dfd07, I added the ability to click links without server assistance.

**Comment by Dykam** [comment]
@killjoy1221, what does this feature add? More extensive parsing? Doesn't it desync the server from the client, click-wise? The server can make any text a link.

**Comment by mattmess1221** [comment]
It just attempts to parse a url if there's no click event. If it fails, it stops there.

**Comment by mattmess1221** [comment]
Closing this.  If you want this done, write it yourself and do a  PR.
