### ISSUE TITLE
Detect more PM formats

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#44]
TabbyChat does not detect PM's with the [formatting that is from CommandBook](https://github.com/sk89q/commandbook/blob/0226f17c04ab4802e3de35e247d7be3e3b21a33b/src/main/java/com/sk89q/commandbook/MessagingComponent.java#L121)
`(To Player): message`
`(From Player): message`

It _does_ [seem to](https://github.com/Dykam/tabbychat/blob/master/src/main/java/acs/tabbychat/core/TabbyChat.java#L589) detect 

> 'From Player' and 'To Player'

So, could you possibly just add in the regex to detect if there is parentheses around it or anything else like brackets?

**Also**, on some servers, there might be a usage of both a plugin's `/msg` and vanilla `/tell`, and I think there might be conflicts, where I use `/msg` while the player responds with `/tell`.

What happens is that when I PM them, it goes to a new tab, but when they respond it does not.
On one server, this was the formatting:
`To Player: message`
`Player whispers: message`

I see that [TabbyChat indeed detects](https://github.com/Dykam/tabbychat/blob/master/src/main/java/acs/tabbychat/core/TabbyChat.java#L593)

> Player whispers to you

But it does not detect that only ^

I am not entirely sure if that was actually custom or not. If it is, I could probably easely just make the replies forward to the tab with the username, but that forces me to actually PM them _first_, to get a "PM tab" created, because only "PM tabs" have pre-written `/msg Player` etc. in them.

**Comment by mattmess1221** [comment]
I'm not the best at regex.  Did I do good?

**Comment by mattmess1221** [comment]
I added a setting
887daa3e456b6909bac3529690800a2611a35158
