### ISSUE TITLE
Lowering opacity makes background 100% transparent but not the latest line

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#45]
Picture:
![](http://i.imgur.com/ejwYLx2.png)

Also video:
http://youtu.be/CTmHUPA_scU

**Comment by mattmess1221** [comment]
It works fine for me.

**Comment by Brottweiler** [comment]
It should not work fine for you... I just tried it now after compiling latest git (not latest now, but yesterday, should make no difference) and this is how it looks like:
![](http://i.imgur.com/qTEjpT4.png)

I will enhance it, look:

![](http://i.imgur.com/zmHEp3M.png)

Does this seriously not happen for you?

**Comment by mattmess1221** [comment]
This is how it looks for me.  Honestly, I have no idea why your text didn't get lowered with it.

![2014-05-31_19 29 24](https://cloud.githubusercontent.com/assets/3409962/3140422/99f7deaa-e91b-11e3-9a6e-c6f0f048dd26.png)

What's your environment like? Such as your OS, Java, graphics and driver versions?

**Comment by Brottweiler** [comment]
GNU/Linux, Java 1.7.0_55. I literally don't see how my graphics driver causes this, but it's nvidia. Can get the card for you if you need that...

More info: I set opacity to 20%, and this is the result:

![](http://i.imgur.com/PGGPadf.png)

Then I set it to 21%, and this is the result:

![](http://i.imgur.com/icSZmJx.png)

20% or lower == completely transparency, except the last line. 21% or higher, it shows the proper opacity I guess.

I understand now that complete transparency is not intended, but It's what I prefer, would it be possible to basically make 10% be like, 0%? Or in some other way do it, so there's no background at all?

**Comment by mattmess1221** [comment]
Are you using Oracle's Java or OpenJDK?

**Comment by Brottweiler** [comment]
OpenJDK.

But I noticed in your screenshot, you do not have the option "Text ignored opacity setting" checked. Check it first, then see if you have the same issue as me.

**Comment by mattmess1221** [comment]
OK, I see it now.  I'll get to it.

**Comment by mattmess1221** [comment]
Apparently, this was a vanilla bug, and Forge just fixed it.  I'm not sure if we inherit or override the method they inserted into, though. I'm not even sure what method they're putting it in. Can you test and report the results?  If it still doesn't work, I'll figure out a way to implement it.

MinecraftForge/MinecraftForge@5c0217d3164aa59 (1181)

**Comment by mattmess1221** [comment]
Nevermind. That is already being done.

**Comment by mattmess1221** [comment]
Fixed. https://github.com/killjoy1221/tabbychat/commit/938c3cf325020255baf0f035c8740ba1b40a42e3
