### ISSUE TITLE
Tab names not ignoring opacity setting

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#47]
If you set Opacity to like 50%, then you have chat **not open**, then get a PM or any other way your tab becomes "highlighted", the entire tab including the text will not ignore the opacity setting.

So setting opacity to 10% which is the minimum, the tab name will be invisible when you have the chat not open.

**Comment by mattmess1221** [comment]
Can't reproduce.

**Comment by Brottweiler** [comment]
Maybe this can clear it up. Here I have lowered my opacity, and I have "text ignores opacity". In this first screenshot, I have the chat opened;

![](http://i.imgur.com/Up22vMu.png)

In this screenshot, it's when I have chat closed, and I have a PM waiting so the tab flashes red.

![](http://i.imgur.com/f4w2WRs.png)

As you can see in the latest screenshot, the text in the tab does **not** ignore the opacity setting.
