### ISSUE TITLE
Tabbychat breaks Macro mod's "inchat" gui screen selection

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#50]
When I use Tabbychat, as soon as I join a server, the "inchat" GUI screen get's "stuck". It's impossible to change the the GUI screen without restarting the game.

**Comment by mattmess1221** [comment]
Can you explain more?  Include your setup and what you were doing.

**Comment by Brottweiler** [comment]
I think this is a way to reproduce the bug:
1. Edit the `inchat` GUI screen, and add for example, a label saying "default inchat gui"
2. Make a new GUI screen called `whatever`.
3. Add a label to "whatever", saying for example, "whatever inchat gui"
4. Join a server (single player should work to I guess)
5. Open chat. It should say the label "default inchat gui"
6. Go to macro settings, then GUI editor.
7. Assign the GUI screen `whatever` to `inchat` instead of the default GUI screen called `inchat`
8. Open chat again. The label should still say "default inchat gui" and **not** "whatever inchat gui"

**Comment by mattmess1221** [comment]
Fixed. https://github.com/killjoy1221/tabbychat/commit/a34e71ebfeb57a259442bb48649b8bf453aecb0f

**Comment by Brottweiler** [comment]
:+1:
