### ISSUE TITLE
Make PM tabs only flash when there is activity in that tab

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#54]
Right now PM tabs flash red every single time there is a message in the "global tab", which gets annoying. PM tabs, or any tab I guess, should only flash red when there is activity in that tab aka. when there is a new message in that PM tab, not otherwise.

**Comment by mattmess1221** [comment]
Let me get this straight.  You are in some tab `[Something]`, someone says something in `[*]`, and `[*]` flashes?  I must be wrong because that doesn't happen for me.

**Comment by Brottweiler** [comment]
No. I get a PM, now I have a new PM tab that is flashing red. 
Now I am in `[*]` **all the time**, and every time I get activity in `[*]`, the PM tab flashes red.

The PM tab should only flash red if there is activity in the PM tab.
