### ISSUE TITLE
Tabs does not flash red when chat is closed

### ISSUE THREAD

**Issue by Brottweiler** [Dykam/tabbychat#59]
If I get a PM, the tab doesn't flash. It is red if I open chat, but if I have chat closed it doesn't flash.

I don't know if this affects regular channel tabs, it may, or may not. I have to test, can't now, but I know this happens with PM's.

**Comment by mattmess1221** [comment]
You're probably in the default channel. In 540b1d4b470b24df3c1d02882be55326cd44150e, I made it so tabs don't flash if you're in the default channel. Switch to another channel and they should start flashing.
