### ISSUE TITLE
Chat doesn't display left side

### ISSUE THREAD

**Issue by Leochan6** [Dykam/tabbychat#60]
So the 1.7.2 version of the mod works fine, but the 1.7.10 version is messed up. 

This is how the 1.7.2 version looks like:
![](http://i.imgur.com/JuHxOBt.png)
And this is how the 1.7.10 version looks like:
![](http://i.imgur.com/YNNsqCG.png)

So if you can't tell what happened, the left side of the chat is cut off.

**Comment by mattmess1221** [comment]
I can't reproduce.  Can you give me the IP of the server that this is
happening on so I can debug it?

**Comment by Leochan6** [comment]
This happens on the mc.hypixel.net server
Hypixel Server

**Comment by mattmess1221** [comment]
Still can't reproduce.  What version are you using? I'm using 1.7.10-1.11.1.65.

**Comment by mattmess1221** [comment]
I know what the issue is now. It's likely that the server is including the first part of the message in the actual first part of the json.

```
{
  text: "[MVP",
  color: cyan,
  extra: [
    {
      text: "+",
      color: red
    },
    {
      text: "] SomeGuysName",
      color: cyan
    }
  ]
}
```

The reason it worked for that last one is because it was created by some chat that knows what its doing.

**Comment by mattmess1221** [comment]
In 1.8, there's a public method used to split chat components that works better than mine, so I will be using that to fix this.

The method is in `GuiScreenRenderingUtils`.

**Comment by mattmess1221** [comment]
Fixed https://github.com/killjoy1221/tabbychat/commit/ac26e3fe2032828dbd0f2f88ed50903d19afaa84
